# Generated by Django 4.2.6 on 2023-12-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=1024)),
                ('embedding_path', models.CharField(blank=True, max_length=1024)),
                ('key_path', models.CharField(blank=True, max_length=1024)),
                ('template_prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon_path', models.ImageField(default='img/babis.jpg', upload_to='frontend/img')),
                ('llm_polit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LLM', to='frontend.embeddings', verbose_name='Embeddings')),
            ],
        ),
    ]
