# Generated by Django 4.2.6 on 2023-10-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeuralNetwork',
            new_name='LLM_model',
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon_path', models.TextField()),
                ('LLM_polit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LLM', to='frontend.llm_model', verbose_name='LLM_model')),
            ],
        ),
    ]
