# Generated by Django 4.2.6 on 2023-10-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_politician_llm_polit'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_model',
            name='name',
            field=models.TextField(default='llm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='politician',
            name='LLM_polit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LLM', to='frontend.llm_model', verbose_name='Llm_model'),
        ),
    ]
