# Generated by Django 4.2.6 on 2023-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_llm_polit_politician_llm_polit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_model',
            name='path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
