# Generated by Django 4.2.6 on 2023-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_rename_path_llm_model_key_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_model',
            name='model_context',
            field=models.TextField(default='Jsem politik.'),
            preserve_default=False,
        ),
    ]
